export type DishCategory = "Mains" | "Breads" | "Starters" | "Desserts" | "Beverages" | "Street Food" | "Continental";

export interface Dish {
	id: string;
	name: string;
	slug: string;
	category: DishCategory;
	price: number;
	veg: boolean;
	spice: "Mild" | "Medium" | "Hot";
	description: string;
	image: string;
}

export const DISH_CATEGORIES: ("All" | DishCategory)[] = ["All", "Mains", "Breads", "Starters", "Desserts", "Beverages", "Street Food", "Continental"];

export const DISHES: Dish[] = [
	{
		id: "biryani",
		name: "Hyderabadi Dum Biryani",
		slug: "biryani",
		category: "Mains",
		price: 280,
		veg: false,
		spice: "Hot",
		description: "Slow-cooked basmati layered with marinated chicken, saffron, fried onions and sealed-pot dum steam. Served with mirchi ka salan and raita.",
		image: "/food-images/dishes/biryani.png",
	},
	{
		id: "butter-chicken",
		name: "Butter Chicken",
		slug: "butter-chicken",
		category: "Mains",
		price: 320,
		veg: false,
		spice: "Medium",
		description: "Tandoor-charred chicken simmered in a silky tomato-cashew gravy finished with cream, butter and a whisper of dried fenugreek.",
		image: "/food-images/dishes/butter-chicken.png",
	},
	{
		id: "paneer-masala",
		name: "Paneer Butter Masala",
		slug: "paneer-masala",
		category: "Mains",
		price: 260,
		veg: true,
		spice: "Medium",
		description: "Hand-cut cottage cheese cubes folded into a velvety makhani gravy with tomato, cream and a gentle warming spice blend.",
		image: "/food-images/dishes/paneer-masala.png",
	},
	{
		id: "naan",
		name: "Garlic Butter Naan",
		slug: "naan",
		category: "Breads",
		price: 50,
		veg: true,
		spice: "Mild",
		description: "Tandoor-baked leavened flatbread brushed with garlic butter and fresh coriander. The ideal sponge for every gravy on the table.",
		image: "/food-images/dishes/naan.png",
	},
	{
		id: "dosa",
		name: "Masala Dosa",
		slug: "dosa",
		category: "Mains",
		price: 140,
		veg: true,
		spice: "Medium",
		description: "Crisp golden rice-and-lentil crepe stuffed with spiced potato masala. Served with sambar, coconut chutney and tomato chutney.",
		image: "/food-images/dishes/dosa.png",
	},
	{
		id: "tandoori-chicken",
		name: "Tandoori Chicken (Half)",
		slug: "tandoori-chicken",
		category: "Starters",
		price: 420,
		veg: false,
		spice: "Hot",
		description: "Chicken leg and thigh marinated overnight in yogurt, kashmiri chili and toasted spices, then charred in the clay tandoor.",
		image: "/food-images/dishes/tandoori-chicken.png",
	},
	{
		id: "samosa",
		name: "Punjabi Samosa (2 pc)",
		slug: "samosa",
		category: "Starters",
		price: 60,
		veg: true,
		spice: "Medium",
		description: "Flaky pastry parcels stuffed with spiced potato and peas, fried to a deep amber. Served with tamarind and mint chutney.",
		image: "/food-images/dishes/samosa.png",
	},
	{
		id: "gulab-jamun",
		name: "Gulab Jamun (2 pc)",
		slug: "gulab-jamun",
		category: "Desserts",
		price: 90,
		veg: true,
		spice: "Mild",
		description: "Khoya-milk dumplings fried golden and soaked in warm cardamom-rose sugar syrup. Served gently heated with a scoop of vanilla.",
		image: "/food-images/dishes/gulab-jamun.png",
	},
	{
		id: "chicken-tikka",
		name: "Chicken Tikka (8 pc)",
		slug: "chicken-tikka",
		category: "Starters",
		price: 360,
		veg: false,
		spice: "Hot",
		description: "Boneless chicken cubes marinated in a double-marinade of hung curd and tikka masala, smoke-finished over charcoal in the tandoor.",
		image: "/food-images/dishes/chicken-tikka.png",
	},
	{
		id: "pasta",
		name: "Penne Arrabbiata",
		slug: "pasta",
		category: "Continental",
		price: 220,
		veg: true,
		spice: "Medium",
		description: "Al dente penne tossed in a fiery Italian tomato-garlic sauce with chilli flakes, olive oil and fresh basil. Finished with parmesan.",
		image: "/food-images/dishes/pasta.png",
	},
	{
		id: "pizza",
		name: "Margherita Pizza",
		slug: "pizza",
		category: "Continental",
		price: 310,
		veg: true,
		spice: "Mild",
		description: "Wood-fired sourdough base spread with San Marzano tomato, torn mozzarella and fresh basil. A clean, classic Neapolitan pie.",
		image: "/food-images/dishes/pizza.png",
	},
	{
		id: "burger",
		name: "Classic Veg Burger",
		slug: "burger",
		category: "Continental",
		price: 180,
		veg: true,
		spice: "Mild",
		description: "Grilled paneer-and-vegetable patty stacked with lettuce, tomato, onion and house smoky mayo in a toasted brioche bun. Fries on the side.",
		image: "/food-images/dishes/burger.png",
	},
	{
		id: "rajma-chawal",
		name: "Rajma Chawal",
		slug: "rajma-chawal",
		category: "Mains",
		price: 190,
		veg: true,
		spice: "Medium",
		description: "Slow-simmered red kidney beans in a thick onion-tomato gravy with whole spices, served over steamed basmati rice. Comfort on a plate.",
		image: "/food-images/dishes/rajma-chawal.png",
	},
	{
		id: "chole-bhature",
		name: "Chole Bhature",
		slug: "chole-bhature",
		category: "Mains",
		price: 150,
		veg: true,
		spice: "Medium",
		description: "Punjabi-style white chickpeas in a tangy spice gravy paired with two pillowy deep-fried bhature. Served with pickled onion and green chutney.",
		image: "/food-images/dishes/chole-bhature.png",
	},
	{
		id: "masala-chai",
		name: "Masala Chai",
		slug: "masala-chai",
		category: "Beverages",
		price: 40,
		veg: true,
		spice: "Mild",
		description: "Assam tea brewed strong with milk, crushed ginger, cardamom and a house chai masala. The perfect cup to close a meal.",
		image: "/food-images/dishes/masala-chai.png",
	},
	{
		id: "veg-fried-rice",
		name: "Veg Fried Rice",
		slug: "veg-fried-rice",
		category: "Mains",
		price: 170,
		veg: true,
		spice: "Medium",
		description: "Wok-tossed long-grain rice with julienned carrot, beans, capsicum and spring onion in a light soy-garlic seasoning. Indo-Chinese staple.",
		image: "/food-images/dishes/veg-fried-rice.png",
	},
	{
		id: "pani-puri",
		name: "Pani Puri (6 pc)",
		slug: "pani-puri",
		category: "Street Food",
		price: 70,
		veg: true,
		spice: "Hot",
		description: "Crisp hollow puris filled with spiced potato, chickpea, tamarind and a pour of mint-coriander pani at the table. The ultimate street bite.",
		image: "/food-images/dishes/pani-puri.png",
	},
	{
		id: "jalebi",
		name: "Hot Jalebi (250g)",
		slug: "jalebi",
		category: "Desserts",
		price: 80,
		veg: true,
		spice: "Mild",
		description: "Funnel-piped fermented batter fried into concentric coils and dunked in saffron sugar syrup. Crisp outside, syrupy within — served hot.",
		image: "/food-images/dishes/jalebi.png",
	},
];
