export interface DemoPage {
	id: string;
	title: string;
	tagline: string;
	description: string;
	screenshot: string;
	bullets: string[];
	category: "Owner" | "Customer" | "Kitchen" | "Compliance";
	accent: string;
}

export const DEMO_PAGES: DemoPage[] = [
	{
		id: "landing",
		title: "Landing Page",
		tagline: "First impression",
		description: "The marketing homepage new restaurateurs land on — QR-ordering pitch, live demo CTA, pricing and an instant signup wizard.",
		screenshot: "/screenshots/01-home-landing.png",
		bullets: ["Hero with animated count-up stats", "Inline login + restaurant signup CTA", "Theme controller + JSON-LD baked in"],
		category: "Owner",
		accent: "from-violet-500/20 to-fuchsia-500/20",
	},
	{
		id: "signup-wizard",
		title: "Signup Wizard",
		tagline: "5-minute onboarding",
		description: "A guided multi-step wizard that takes a brand-new owner from zero to a fully configured restaurant, menu and table QRs in one sitting.",
		screenshot: "/screenshots/02-restaurant-signup-wizard.png",
		bullets: ["Business details, GST & theme setup", "Auto-generated table QR codes", "Seeded demo menu to start selling today"],
		category: "Owner",
		accent: "from-fuchsia-500/20 to-pink-500/20",
	},
	{
		id: "dashboard-overview",
		title: "Dashboard Overview",
		tagline: "Mission control",
		description: "The single-screen cockpit an owner checks every morning — live revenue, active tables, order requests and shift status at a glance.",
		screenshot: "/screenshots/03-dashboard-overview.png",
		bullets: ["Real-time revenue & order counters", "Active tables and kitchen load", "Quick actions for every role"],
		category: "Owner",
		accent: "from-violet-600/20 to-purple-500/20",
	},
	{
		id: "analytics",
		title: "Analytics",
		tagline: "Numbers that move",
		description: "Revenue breakdown by hour, day and item; peak-hour heatmaps; top performers and AI-flagged upsell opportunities.",
		screenshot: "/screenshots/03a-dashboard-analytics.png",
		bullets: ["Hourly revenue & peak-hour heatmap", "Best-selling items + margin view", "AI suggestions for menu pruning"],
		category: "Owner",
		accent: "from-emerald-500/20 to-teal-500/20",
	},
	{
		id: "menu-editor",
		title: "Menu Editor",
		tagline: "Drag, drop, sell",
		description: "A visual menu builder — add items, set prices, mark veg/non-veg, attach photos, toggle availability and reorder categories live.",
		screenshot: "/screenshots/03d-dashboard-menu.png",
		bullets: ["Live category & item reordering", "Photo, spice level & notes per item", "One-tap hide when 86'd for the night"],
		category: "Owner",
		accent: "from-amber-500/20 to-orange-500/20",
	},
	{
		id: "settings-tables-qr",
		title: "Tables & QR Settings",
		tagline: "One scan, one table",
		description: "Define floor-plan tables, print per-table QR standees and toggle direct-order vs. table-order modes per station.",
		screenshot: "/screenshots/04-settings-tables-qr.png",
		bullets: ["Per-table QR generation & download", "Direct-order landing pages", "Table status syncs to kitchen & cashier"],
		category: "Owner",
		accent: "from-cyan-500/20 to-sky-500/20",
	},
	{
		id: "kitchen-display",
		title: "Kitchen Display",
		tagline: "No more paper KOTs",
		description: "A sound-alerted, color-coded order board the kitchen actually wants to use — accept, prepare, mark ready, all one tap.",
		screenshot: "/screenshots/05-kitchen-display.png",
		bullets: ["Spice-level + notes highlighted per ticket", "Accept → Preparing → Ready workflow", "Audit-logged, no ticket ever vanishes"],
		category: "Kitchen",
		accent: "from-rose-500/20 to-red-500/20",
	},
	{
		id: "customer-menu",
		title: "Customer Menu",
		tagline: "Browse, drool, order",
		description: "The phone-first menu your diners see after scanning the QR — big photos, search, category chips and one-tap add to cart.",
		screenshot: "/screenshots/06-customer-restaurant-menu.png",
		bullets: ["High-res dish photography", "Search, filter & spice-level customize", "Works offline-cached as a PWA"],
		category: "Customer",
		accent: "from-violet-500/20 to-indigo-500/20",
	},
	{
		id: "table-ordering",
		title: "Table Ordering",
		tagline: "Order from your seat",
		description: "Diners add items, leave notes, review their cart and place the order straight to the kitchen — no waiter flag-down needed.",
		screenshot: "/screenshots/07-customer-table-ordering.png",
		bullets: ["Live cart with quantity & notes", "Apply coupons & loyalty points", "Pay online or flag for cashier"],
		category: "Customer",
		accent: "from-fuchsia-500/20 to-purple-500/20",
	},
	{
		id: "reviews",
		title: "Reviews & Ratings",
		tagline: "Public proof",
		description: "A public reviews tab on every restaurant page — star ratings, photos and owner replies that feed back into SEO.",
		screenshot: "/screenshots/08-customer-reviews.png",
		bullets: ["Star ratings with photo reviews", "Owner reply thread per review", "Negative reviews routed to inbox"],
		category: "Customer",
		accent: "from-amber-500/20 to-yellow-500/20",
	},
	{
		id: "cashier-billing",
		title: "Cashier Billing",
		tagline: "Close every table",
		description: "A cashier screen that consolidates table orders, splits bills, applies tips and prints the final tamper-proof bill.",
		screenshot: "/screenshots/dashboard_active.png",
		bullets: ["Split & merge bills per table", "Digital tips split to shift staff", "Shift open / X-report / Z-report"],
		category: "Owner",
		accent: "from-emerald-500/20 to-green-500/20",
	},
	{
		id: "inventory",
		title: "Inventory & Variance",
		tagline: "Catch the leak",
		description: "Track stock-in, wastage and physical counts; the system flags variance between expected and actual consumption per ingredient.",
		screenshot: "/screenshots/dashboard_requests.png",
		bullets: ["Stock-in, wastage & physical count", "Auto-deduct on every KOT", "Variance report flags theft & leakage"],
		category: "Compliance",
		accent: "from-teal-500/20 to-cyan-500/20",
	},
	{
		id: "gst",
		title: "GST & e-Invoice",
		tagline: "Filed before you sleep",
		description: "Auto-computed CGST/SGST/IGST per item, IRP e-invoice generation and one-click GSTR-1 / GSTR-3B exports.",
		screenshot: "/screenshots/restaurant_cart.png",
		bullets: ["Per-item HSN + GST rate engine", "IRP e-invoice with signed QR", "GSTR-1 & 3B CSV/JSON export"],
		category: "Compliance",
		accent: "from-indigo-500/20 to-violet-500/20",
	},
	{
		id: "audit-chain",
		title: "Audit Chain",
		tagline: "The bill that cannot lie",
		description: "Every bill, KOT and refund is hash-chained. Any after-the-fact edit breaks the chain visibly — making theft mathematically detectable.",
		screenshot: "/screenshots/restaurant_qrcode_dark.png",
		bullets: ["SHA-256 hash-linked bill chain", "Tamper breaks the chain — instantly visible", "Public verify endpoint for auditors"],
		category: "Compliance",
		accent: "from-slate-500/20 to-zinc-500/20",
	},
	{
		id: "feedback",
		title: "Feedback Inbox",
		tagline: "Negative reviews, intercepted",
		description: "A tokenised feedback flow routes unhappy diners to a private inbox before they reach Google — and triggers WhatsApp follow-ups.",
		screenshot: "/screenshots/08-customer-reviews.png",
		bullets: ["Tokenised post-meal feedback link", "Negative feedback → private inbox", "Auto WhatsApp recovery offer"],
		category: "Customer",
		accent: "from-pink-500/20 to-rose-500/20",
	},
	{
		id: "direct-order",
		title: "Direct Order Landing",
		tagline: "Zero commission orders",
		description: "A branded direct-order landing page for pickup & delivery that bypasses aggregators entirely — keeping the 20-25% commission.",
		screenshot: "/screenshots/06-customer-restaurant-menu.png",
		bullets: ["Own domain & branded URL", "Pickup + delivery with live ETA", "Aggregator orders still import here"],
		category: "Customer",
		accent: "from-violet-500/20 to-fuchsia-500/20",
	},
];
